on:
 workflow_dispatch:
   inputs:
     environment:
       description: 'Select the environment'
       required: true
       type: choice
       options:
         - dev
         - qa
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying to ${{ github.event.inputs.environment }} environment"
